project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  pdf: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



